### ISSUE TITLE
OpenZWave daemon without the HASS.IO addone

### ISSUE THREAD

**Issue by yolani** [cgarwood/homeassistant-zwave_mqtt#100]
HI there,

are there any implications regarding using the OpenZwave-Daemon natively without the HASS.IO addon, does it add any functionality that is necessary?

I am not using HASS.IO but rather the native docker image.

If this is no problem, maybe a hint should be added to the Quickstart-Section of the README.

**Comment by marcelveldt** [comment]
Expert users are free to use the OZW daemon directly it does not add or remove any functionality.
We try to keep the instructions as simple as possible, not describing every possible situation.
