### ISSUE TITLE
Duplicate devices with .12 homeassistant-zwave_mqtt

### ISSUE THREAD

**Issue by silfa718** [cgarwood/homeassistant-zwave_mqtt#109]
- Home Assistant version: 109.04b
- ozwdaemon version or add-on version: 1.0.15
- homeassistant-zwave_mqtt version: .12

**Comment by marcelveldt** [comment]
Did you read the release notes ?
Mostly the part in bold font and big letters "BREAKING CHANGE".

You will have to remove the integration and re-add it to remove the ghost devices.
