### ISSUE TITLE
New binary sensor not initializing correctly at HA startup

### ISSUE THREAD

**Issue by kevinkahn** [cgarwood/homeassistant-zwave_mqtt#110]
- Home Assistant version: 108.1
- ozwdaemon version or add-on version: container pull as of 4/19/20

Like the new binary sensor support you just added but possibly a small bug.  Situation: 2 garage doors one open, one closed.  Using the old access control value one door showing open (22) and one showing closed (23).  New binary sensors for the doors also showing correct one open one closed.  Now restart HA.  After restart the access control values are still showing correctly as 22/23 but the new binary sensors are both showing closed.  Perhaps not initializing quite right at start up?  Once HA is up changes in door state look great.

**Comment by marcelveldt** [comment]
Thanks for spotting this. Will be fixed later today.

**Comment by marcelveldt** [comment]
This is now fixed. A new version has been released.
