### ISSUE TITLE
Thermostat has multiple climate entities

### ISSUE THREAD

**Issue by kpine** [cgarwood/homeassistant-zwave_mqtt#116]
- Home Assistant version: 0.109.0
- ozwdaemon version or add-on version: latest
- homeassistant-zwave_mqtt version: 0.0.14

My thermostat which supports COMMAND_CLASS_THERMOSTAT_MODE has 4 separate climate entities, one for each setpoint. These should be combined into a single climate entity, as is done in HA core Z-Wave.

![image](https://user-images.githubusercontent.com/791794/80739192-e3e9d200-8aca-11ea-9c30-e754c149e619.png)

**Comment by marcelveldt** [comment]
Can you provide me with a mqtt dump please so I can test this ?

**Comment by kpine** [comment]
Sure, but the problem is the discovery schema. Compare the one here vs. HA core.

**Comment by marcelveldt** [comment]
> Sure, but the problem is the discovery schema. Compare the one here vs. HA core.

May be true but I'd still like to receive the dump ;-)

**Comment by kpine** [comment]
You're too fast! Here it is.

[mqtt_dump.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4559963/mqtt_dump.txt)

**Comment by marcelveldt** [comment]
Thanks, this will allow me to reproduce as I do not own climate devices.

**Comment by kpine** [comment]
FYI, here's what's missing: https://github.com/home-assistant/core/blob/d43617c41d6507f2d2b77aadf4fa1ebaf0058b14/homeassistant/components/zwave/discovery_schemas.py#L95

**Comment by marcelveldt** [comment]
Ah, I guess that was added to the core zwave after this project was initiated ;-)

**Comment by kpine** [comment]
I think that's true. I should have remembered to mention it before.

Also, this core issue should be fixed: https://github.com/home-assistant/core/issues/30180

**Comment by marcelveldt** [comment]
> I think that's true. I should have remembered to mention it before.
> 
> Also, this core issue should be fixed: [home-assistant/core#30180](https://github.com/home-assistant/core/issues/30180)

I'd rather focus on getting this project stable but feel free to submit a PR for that specific issue.

**Comment by joshtbernstein** [comment]
@marcelveldt Do you still need a mqtt dump from me also? Thanks to @kpine for opening this issue.

**Comment by marcelveldt** [comment]
> @marcelveldt Do you still need a mqtt dump from me also? Thanks to @kpine for opening this issue.

If you own a different thermostat than kpine: yes please

**Comment by kpine** [comment]
> I'd rather focus on getting this project stable but feel free to submit a PR for that specific issue.

Instead, I should have said, please don't break those thermostat types when fixing this, because they aren't broken here yet.

**Comment by marcelveldt** [comment]
> > I'd rather focus on getting this project stable but feel free to submit a PR for that specific issue.
> 
> Instead, I should have said, please don't break those thermostat types when fixing this, because they aren't broken here yet.

Haha, true. Let's try to make this version a lot better!

**Comment by cgarwood** [comment]
Ah yeah, the climate change in the current `core` component came after I copied the discovery schema's over to this project and this project was never updated to include them. I had actually forgotten about that until now.

**Comment by marcelveldt** [comment]
> Ah yeah, the climate change in the current `core` component came after I copied the discovery schema's over to this project and this project was never updated to include them. I had actually forgotten about that until now.

No problem, I'm working through it now. Unfortunately it wasn't as easy as copying the discovery schema.

**Comment by joshtbernstein** [comment]
@marcelveldt Here you go! Please let me know what else I can do to help with this :-)

[mqtt_dump.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4560563/mqtt_dump.txt)

**Comment by Dinth** [comment]
Im also seeing this.
![Screenshot from 2020-05-01 12-50-32](https://user-images.githubusercontent.com/313674/80803539-7f9e3f80-8baa-11ea-9e28-0fc05ba11f22.png)
https://gofile.io/?c=rrUiJ2

**Comment by joshtbernstein** [comment]
@marcelveldt I just pulled down the master using HACS and I'm not seeing any change, I still have two climate entities. I removed and readded the integration and no change. Anything I can do to help troubleshoot?

**Comment by marcelveldt** [comment]
> @marcelveldt I just pulled down the master using HACS and I'm not seeing any change, I still have two climate entities. I removed and readded the integration and no change. Anything I can do to help troubleshoot?

No, just have some patience ;-)

**Comment by joshtbernstein** [comment]
> No, just have some patience ;-)

Sorry, I'll be patient!

**Comment by marcelveldt** [comment]
I just published version .15 to HACS, please have a test with that.
As we're already implementing the code into core Hass it would be great to get some feedback if this issue is resolved.

WARNING: version .15 contained a change to the internal id matching so it is normal that you need to rename your entities/devices again.

**Comment by kpine** [comment]
Looks good to me. My CT32 with thermostat mode has a single climate entity now.

There is something wrong with the preset behavior though, but I need to look more. Will log that separately if it turns out to be an issue.

**Comment by marcelveldt** [comment]
As the originally reported issue is resolved, I'll close this issue.
The climate platform will be merged to the core implementation with these adjustments included.

**Comment by marcelveldt** [comment]
This issue will be fixed in the core implementation so please keep an eye on the next beta version of Home Assistant. Thanks for your help testing and reporting the issue.
