### ISSUE TITLE
New set of entities with default ids and names

### ISSUE THREAD

**Issue by achurak** [cgarwood/homeassistant-zwave_mqtt#129]
- Home Assistant version: 0.109.4
- ozwdaemon version or add-on version:
- homeassistant-zwave_mqtt version: 0.15

After upgrading the integration from 0.14 to 0.15 all the entities I changed the entity ids and names for became unavailable and a new set of entities was added with the default entity ids and names. Will that be happening with every update or was it a bug? Very frustrating, though I understand it's still in pre-release stage.

**Comment by cgarwood** [comment]
That was a breaking change to fix an issue with supporting multiple qt-openzwave instances

**Comment by achurak** [comment]
> 
> 
> That was a breaking change to fix an issue with supporting multiple qt-openzwave instances

Thanks for clarifying that! Just for the future, how was I supposed to know what it was going to break? I did go through the release's changes and even saw the "breaking" term being used, but nowhere did I see the change/consequences being actually explained. Did I miss it somehow and where should I look next time?

**Comment by marcelveldt** [comment]
The README:

**This is an early beta/pre-release and there are still significant limitations**

**Comment by marcelveldt** [comment]
BTW: We're in the process of introducing the new integration into Home Assistant core :-)
This repo is to be considered for testers (not production ready)..

**Comment by achurak** [comment]
> 
> 
> The README:
> 
> **This is an early beta/pre-release and there are still significant limitations**

While I appreciate what you're doing here and the fact that despite being a pre-release it's been working pretty stable so far, I still think it's one thing to expect things to not work at all or correctly and expect breaking changes during the testing stage and it's another thing for these breaking changes to happen without even a single sentence explaining what's about to break.

Hass itself technically is still in beta stage with plenty of breaking changes, but they always warn users about these changes. Take it as you will.

**Comment by marcelveldt** [comment]
Please keep an eye on the release of zwave_mqtt in core Home Assistant. There won't be any more updates to this component. Thanks for your help testing!
