### ISSUE TITLE
All devices and entities visible but unavailable after installation.

### ISSUE THREAD

**Issue by jef-pearlman** [cgarwood/homeassistant-zwave_mqtt#130]
- Home Assistant version: 0.109.5 (HassOS 3.13/Supervisor 220)
- ozwdaemon version or add-on version: 1.0.16
- homeassistant-zwave_mqtt version: 0.0.15
- mqtt dump: [mqtt_dump.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4595769/mqtt_dump.txt)
- Just noting this is on a RPi 2 B, in case that could be a problem.  (Am upgrading to RPi 4 this weekend.)

tl;dr: My zwave devices and entities appear, but all are permanently unavailable.

My HA system is relatively new, and I was having a zwave event issue, so I decided to give this new system a try to ease the later pain of transitioning, avoid that issue, and maybe take advantage of some ozw1.6 improvements.  I followed the instructions in the README; all configurations were left at default except changing the USB device to point to my controller.

After a couple of hiccups, I got things going to the point where most or all of my existing z-wave network (29 devices, 75 entitites) appear in HA.  However, all of the devices and entities are permanently unavailable, so can't be controlled or monitored.  As far as I can tell, none has ever been available.  This situation has stayed the same through multiple reboots, HA restarts, a few component updates, and a decent amount of uptime (> 12 hours continuous).

The Open Z-Wave Daemon logs show a bunch of activity and after a few minutes ends with this line:
2020-05-07 13:50:13,337 INFO exited: ozwdaemon (exit status 0; expected)
There are no further messages, even when devices are manually used.

The Mosquitto broker logs just show a connection and not much else.

I'd appreciate any assistance; it's not clear to me what my next step should be.  Many thanks!

p.s. Apologies if this is not the appropriate place; I wasn't sure if this was really an "issue" or just a tech support request.  I might suggest that you add a link in the README if you have a preferred forum for such requests.

**Comment by Mystichrome** [comment]
Saw this as well after upgrading to 0.0.15.  Re-installed 0.0.14 and all the devices and entities became available again.

**Comment by jef-pearlman** [comment]
> 
> 
> Saw this as well after upgrading to 0.0.15. Re-installed 0.0.14 and all the devices and entities became available again.

Thanks!  That worked for me.  I'll keep it at 14 but keep watching this issue in case there's a way I can help debug it.  (My network can be non-functional for a while.)

**Comment by achurak** [comment]
> 
> 
> > Saw this as well after upgrading to 0.0.15. Re-installed 0.0.14 and all the devices and entities became available again.
> 
> Thanks! That worked for me. I'll keep it at 14 but keep watching this issue in case there's a way I can help debug it. (My network can be non-functional for a while.)

Could it be the same issue: https://github.com/cgarwood/homeassistant-zwave_mqtt/issues/129

**Comment by marcelveldt** [comment]
Please keep an eye on the release of zwave_mqtt in core Home Assistant. There won't be any more updates to this component. Thanks for your help testing!

**Comment by jef-pearlman** [comment]
> 
> 
> Please keep an eye on the release of zwave_mqtt in core Home Assistant. There won't be any more updates to this component. Thanks for your help testing!

Thanks!  FWIW, I reverted to the default integration after running into some more issues, but I know development is happening fast.  I see what I assume is the new one in the add-on store marked incompatible, presumably to keep people form using it until it's ready.  Once it's available that way I'll give it another shot and report any new issues then.
