### ISSUE TITLE
Aeon labs gen 6 dimmer module (ZW099) not working

### ISSUE THREAD

**Issue by ppruchnicki** [cgarwood/homeassistant-zwave_mqtt#134]
- Home Assistant version: 0.108.6
- ozwdaemon version or add-on version: 1.0.16
- homeassistant-zwave_mqtt version: 0.0.15
[mqtt_dump.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4609575/mqtt_dump.txt)

   I have an aeon labs gen 6 dimmer module (ZW099) since the current development of the add-on is limited to dimmers it should work but the device does not show up in the integration sections. Two other multisensors has showed so the add-on is working. Is this device currently unsupported or there is something wrong with the add-on/setup?

**Comment by austwhite** [comment]
Is this module still not working in latest versions using HA 0.110 ? 
I ask because I have several of these and if they don't work then I will not even attempt migration.

**Comment by marcelveldt** [comment]
The status of this custom component should be considered as stale, all development is now going on in Home Assistant core. This repo is only maintained to keep track of the state and some conversation. Please report any issues you have to the Home Assistant issue tracker: https://github.com/home-assistant/core/issues

PS: The Aeon labs dimmer should work fine, I own multiple of them.
