### ISSUE TITLE
Abort config flow if MQTT integration isn't already configured

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/homeassistant-zwave_mqtt#16]
This component requires the MQTT component in Home Assistant to be set up already. We should abort the config flow if MQTT isn't already setup.

**Comment by marcelveldt** [comment]
If you try to setup the integration when MQTT is not setup it will fail silently in the frontend, it just returns to the list. We need to show a nice message what's going on.

**Comment by marcelveldt** [comment]
@MartinHjelmare looks like this is fixed in the core implementation ?

**Comment by MartinHjelmare** [comment]
Yeah, we worked around it by making the mqtt integration an `after_dependencies`. We want to change this later but currently all the `dependencies` are set up before the flow is started, so it's impossible to show feedback to the user if using `dependencies` that aren't available.
