### ISSUE TITLE
Cleanup entities/registries when a node is removed

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/homeassistant-zwave_mqtt#18]
When a node is removed we should remove the entities from Home Assistant, clear them from the entity registry, and clear the node from the device registry.

May require upstream python-openzwave-mqtt updates to fire node removed events.

**Comment by balloob** [comment]
We can copy the code that Hue uses for this https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/hue/helpers.py#L21-L31

**Comment by marcelveldt** [comment]
This is a tricky one as I've learned today. When OZW is restarting it will remove and re-add all nodes (and values). We'll have to separate the 2 scenarios:

1) OZW is restarting or a node is being refreshed. The node and/or values are removed and will be re-added later on. We mark the entities as unavailable/offline when this happens, in any case it should not be removed from the device and entity registry.

2) A node is being removed on purpose by the user by issuing the removenode command.
OZW will fire an event when this command has been successfully executed, containing the node_id in the message details.
Only in this case we may cleanup the node's entities and device itself from entity and device registry.

**Comment by marcelveldt** [comment]
Closed by #93
