### ISSUE TITLE
Add climate platform

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/homeassistant-zwave_mqtt#2]
Need to add climate platform. Discovery schemas were copied from the existing zwave component.

**Comment by kpine** [comment]
There hasn't been any action on this one, anyone planning on working on it in the near future? If not, I could take a look, but I might be a little slow due to time constraints. I just don't want to duplicate anyone's efforts if it's next on the list.

**Comment by Dinth** [comment]
+1 
Im happy to do some testing if needed, ive got several EUR_SPIRITZ radiator thermostats on my mesh.

**Comment by marcelveldt** [comment]
climate platform is now available in version .14 thanks to #101
