### ISSUE TITLE
Add migration path from zwave2mqtt

### ISSUE THREAD

**Issue by techguydave** [cgarwood/homeassistant-zwave_mqtt#20]
It seems like a lot of people (myself included) use the zwave2mqtt tool instead of the built-in component, so it may be a good idea to also see if a migration from that is feasible.

**Comment by RualdOrdelman** [comment]
+1 

I'm using Zwave2mqtt with OpenZwave 1.6 build.

**Comment by cgarwood** [comment]
I personally have no intentions to add a migration path from zwave2mqtt since it's not an official Home Assistant component and I've never used it, but I'd accept a PR if someone else wanted to write it.

**Comment by techguydave** [comment]
I would be interested in attempting a PR for this. Probably won't get to it for a few weeks, though.

**Comment by jfrux** [comment]
I think there is also value in updating readme to share the mission of this component over the missions of zwave2mqtt for those that are less experienced in this setup.

I'd LOVE to know what the benefits of this over the other options are just because I've not had much luck taking the leap to zwave2mqtt, etc.

**Comment by shbatm** [comment]
>I'd LOVE to know what the benefits of this over the other options

Came here looking for this. I've been using zwave2mqtt for a year now and it's very stable, curious to know what advantages this would have.

**Comment by balloob** [comment]
Please stay on topic and create a new issue for other topics.

**Comment by marcelveldt** [comment]
I'm going to close this issue as there are no intentions to create a migration path from zwave2mqtt as it's just a **different Z-wave implementation** and has nothing to do with this project. We are focusing on getting this new Z-wave support available in Home Assistant with userfriendly set-up and configuration and we'll care for a migration from the current zwave integration to the new.

For a more clear explanation of differences, see this post on the forums:
https://community.home-assistant.io/t/update-on-the-z-wave-integration-home-assistant-dev-docs/169045/41
