### ISSUE TITLE
[question] Setting up the MQTT Integration to work with this plugin

### ISSUE THREAD

**Issue by varet80** [cgarwood/homeassistant-zwave_mqtt#49]
I am trying to setup the integration. Is there some guide on how to configure MQTT integration to make it work?

I suspect I am doing something wrong with the prefix. I do see my broker filling in with topics from qt-openzwave.

**Comment by marcelveldt** [comment]
Nothing special is needed actually. Just setup a MQTT broker in HomeAssistant and you're all set.
Leave the prefix empty so it will default to OpenZwave.

**Comment by anthonyangel** [comment]
Is there an option to set username / password to connect to the mqtt broker?

**Comment by marcelveldt** [comment]
Are you using the supervisor/hassio add-on to run openzwave daemon? In that case it's all handles automagically for you as it adds a bridge to handle authenticated mqtt.

the regular openzwave docker does not yet have support for authenticated mqtt...

**Comment by marcelveldt** [comment]
Will close the issue as it seems resolved. Please reopen if it's still valid. If you have another question/issue, please submit a new issue. Thanks!
