### ISSUE TITLE
Parallel install with existing native z-wave integration

### ISSUE THREAD

**Issue by craigrallen** [cgarwood/homeassistant-zwave_mqtt#51]
Hi,

I've been trying to test this on a dev platform and wanted to see if I can run it in parallel with the existing native z-wave integration. The aim is to see if I can migrate compatible devices to the new integration and leave incompatible devices on the native platform for the moment. I suspect that the native integration locks the usb port for comms to the z-wave stick and the new integration cannot pull down the list of devices on the stick.

Any advice appreciated.

**Comment by cgarwood** [comment]
Unfortunately not possible as only one process can use the USB stick at a time

**Comment by marcelveldt** [comment]
If all you want right now is test the new implementation I'd advice you to make a copy of your hass config.
After that remove the default zwave from your config and add this one.
You will have to reconfigure your entity configuration/naming but you should be able to do a fair amount of testing. Once done testing, place your config backup back.

So, true that you can only have one OZW instance talking to you zwave stick at one time but you can switch back and forth between implementations if you'd like.

For basic lights, switches and sensors this implementation is already pretty stable.
