### ISSUE TITLE
Which Zwave sticks are supported?

### ISSUE THREAD

**Issue by warllo54** [cgarwood/homeassistant-zwave_mqtt#54]
The readme states "Supported Z-wave dongle compatible with OpenZWave 1.6" Which are supported?

Is any zwave dongle running 1.6 supported?

**Comment by balloob** [comment]
This list some working controllers. It's the same as the existing Z-Wave integration. https://www.home-assistant.io/docs/z-wave/controllers/#supported-z-wave-usb-sticks--hardware-modules

**Comment by warllo54** [comment]
@balloob Thanks!

**Comment by Fishwaldo** [comment]
700 series controllers are not *yet* supported
