### ISSUE TITLE
Home Assistant not responding to switch presses

### ISSUE THREAD

**Issue by anthonyangel** [cgarwood/homeassistant-zwave_mqtt#58]
[mqtt_dump.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4201911/mqtt_dump.txt)
- Home Assistant version: 0.105.3
- ozwdaemon version or add-on version: 1.0.10
- homeassistant-zwave_mqtt version: 0.0.5

I have 3 Steinel IS 140-2 PIR / Floodlights and about 15 Fibaro dimmer 2's, all connected in secure mode. Each of the Fibaro modules presents 2 switches to Home Assistant, when I try to toggle any switch the lights don't change, and the switch immediately resets itself back in Home Assistant. For the Steinel PIRs the switch resets itself, but the light does toggle

Attached is a dump (taken over 60 seconds)

**Comment by anthonyangel** [comment]
I've taken another dump over 2 minutes, as it looked like the 1st one only had events from the controller, and not from any nodes

[mqtt_dump.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4201945/mqtt_dump.txt)

**Comment by marcelveldt** [comment]
Can you try to restart the OZW daemon ?
After the restart wait a few minutes and restart hass. We still need to make thing a little more robust. For example if you restart the daemon, the connection in hass is lost and will not auto recover.

**Comment by anthonyangel** [comment]
It looked like I had to press each light switch in order to sync the system, and allow control for Home Assistant. This seems strange to key, as they're powered devices so shouldn't have to be woken up.

It's working now though, thanks

**Comment by marcelveldt** [comment]
Hmm, that's strange indeed. Recently there's been a big change in OZW to fix a long standing issue that might have caused this to appear.  We'll keep an eye on it.
