### ISSUE TITLE
Include doesn't seem to work properly

### ISSUE THREAD

**Issue by isabellaalstrom** [cgarwood/homeassistant-zwave_mqtt#66]
- Home Assistant version: 0.105.5
- ozwdaemon version or add-on version: 1.0.12
- homeassistant-zwave_mqtt version: 0.0.7

I'm having trouble with including sensors. I can see in the mqtt that something has happened, but I can't see any information about the recently included node (3). It's a Aeotec door sensor (same as node 2). The mqtt dump is from a restart after including. I can dump more info it you tell me what you need.
[dump_mqtt2.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4243601/dump_mqtt2.txt)

**Comment by marcelveldt** [comment]
You see the new node 3 in our mqtt tree ?

**Comment by isabellaalstrom** [comment]
Not sure what you mean by mqtt tree? If you look in the dump file it's there but with minimal info.

```
OpenZWave/1/node/3/,{    "NodeID": 3,    "NodeQueryStage": "ProtocolInfo",    "isListening": true,    "isFlirs": false,    "isBeaming": false,    "isRouting": false,    "isSecurityv1": false,    "isZWavePlus": false,    "isNIFRecieved": true,    "isAwake": true,    "isFailed": false,    "MetaData": {        "OZWInfoURL": "",        "ZWAProductURL": "",        "ProductPic": "",        "Description": "",        "ProductManualURL": "",        "ProductPageURL": "",        "InclusionHelp": "",        "ExclusionHelp": "",        "ResetHelp": "",        "WakeupHelp": "",        "ProductSupportURL": "",        "Frequency": "",        "Name": "",        "ProductPicBase64": ""    },    "Event": "nodeProtocolInfo",    "TimeStamp": 1581584693,    "NodeManufacturerName": "",    "NodeProductName": "",    "NodeBasicString": "Routing Slave",    "NodeBasic": 4,    "NodeGenericString": "Notification Sensor",    "NodeGeneric": 7,    "NodeSpecificString": "Notification Sensor",    "NodeSpecific": 1,    "NodeManufacturerID": "0x0000",    "NodeProductType": "0x0000",    "NodeProductID": "0x0000",    "NodeBaudRate": 0,    "NodeVersion": 0}
```

**Comment by kpine** [comment]
> `"NodeQueryStage": "ProtocolInfo"`

The node probably went to sleep before the interview process completed. Push the "Action button" one time (or 2x in one second if included securely) to send the node info and see if it gets updated. Try enough times until the query stage says "Complete".

**Comment by isabellaalstrom** [comment]
You are correct, of course :) I didn't realize at all. It came in fine now.
