### ISSUE TITLE
After adding node, Device and Entities list are confused until restart

### ISSUE THREAD

**Issue by kpine** [cgarwood/homeassistant-zwave_mqtt#68]
- Home Assistant version: 0.106.1
- ozwdaemon version or add-on version: 0.1
- homeassistant-zwave_mqtt version: 0.0.7

I added a new node using the `zwave_mqtt.add_node` service. The node and its entities are detected immediately, but almost none of them are associated with the "ZWave over MQTT" integration, and instead the "sensor" integration. They are marked as read-only because they do not have a unique ID.

![image](https://user-images.githubusercontent.com/791794/75616124-16df0c00-5b02-11ea-84d6-c62b1bbc753f.png)
![image](https://user-images.githubusercontent.com/791794/75616127-278f8200-5b02-11ea-9c1d-29e2919a4e37.png)

![image](https://user-images.githubusercontent.com/791794/75616147-6faea480-5b02-11ea-81f6-ff491bc705d6.png)

But if I click on an entity and go to settings, it seems to realize that it is part of the device and integration, so something is confused.

![image](https://user-images.githubusercontent.com/791794/75616140-61f91f00-5b02-11ea-882e-a73e61685251.png)

I then checked the device entity registry files and they seem to be correct, each entity has a unique ID and is associated with the device. So, I'm not sure if this is an integration bug or HA bug. After restarting HA, everything looks normal, but I would hope a restart is unnecessary. I've attached files from before the restart.

[files.zip](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4271089/files.zip)

**Comment by marcelveldt** [comment]
True, this still needs fixing. Thanks for the reminder ;-)

**Comment by marcelveldt** [comment]
Issue reproduced step by step

When adding a node, it's values are available before OZW downloads the detailed info for the device. So when an entity is added to the hass entity/device registry, the device and model properties are not yet available. Those details do get filled after some time (few seconds till few minutes) and the entities change their default name accordingly but the device registry does not refresh/update.

We have to somehow "kick" the device registry to update the device details.

**Comment by marcelveldt** [comment]
This one is fixed once #94 is merged.
