### ISSUE TITLE
Should at some point decide/document best practice for fielding central scene events

### ISSUE THREAD

**Issue by kevinkahn** [cgarwood/homeassistant-zwave_mqtt#71]
Central scene events seem to have been standardized to some degree in openwave.  The return a label and a value label as well as string versions of these.  It isn't clear which of these (any? all?) can be assumed standardized across devices but they do get used in automations testing for things like multiple button clicks.  We should have at least a "best practice" regarding how to catch these events.  I.e. whether to use the string or the code or whether there is intent to further integrate them in the HA support in some way.

**Comment by Fishwaldo** [comment]
The Labels (and each corresponding value) is fixed and won’t change. (Apart from localization/language, hence you should test the value not the label) What does change is the actual list of values exposed by each ValueID. 

The ValueList exposed will only contain the Scene Event Types the device supports. (Eg if it doesn’t support “double click” then double click won’t appear in the list. - so it’s like a enumeration).

**Comment by kevinkahn** [comment]
Great.  This should get documented at some point in the HA integration.  Thanks.
