### ISSUE TITLE
Can’t decrypt packet

### ISSUE THREAD

**Issue by mcondren** [cgarwood/homeassistant-zwave_mqtt#74]
- Home Assistant version: .106
- ozwdaemon version or add-on version: 
- homeassistant-zwave_mqtt version: 0.0.7

  I set this up to help test but I’m getting a ‘can’t decrypt packet’ error in the ozwdaemon logs for my securely paired devices.  Did I miss a step to import the existing encryption key?

**Comment by balloob** [comment]
Make sure you configure the hassio addon correctly https://github.com/marcelveldt/hassio-addons-repo/tree/master/ozwdaemon#configuration

If you are not using the addon, please see the ozwdaemon documentation to specify your key.
