### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by steinerl** [cgarwood/homeassistant-zwave_mqtt#79]
Hello,

please add/specify a LICENSE to make it clear that we are legally allowed to use and modify the code in this repository.

Thanks!

**Comment by marcelveldt** [comment]
License has been added. That said, contributions are welcome!

EDIT: I'm mistaken... License has been added to the upstream library but not yet on the component code. We'll do ASAP.

**Comment by balloob** [comment]
Let's instead just merge this integration into HA 👍

**Comment by marcelveldt** [comment]
Code will be merged into Home Assistant as native integration. As of that point Home Assistant's license will apply.
