### ISSUE TITLE
Add battery sensors

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/homeassistant-zwave_mqtt#8]
COMMAND_CLASS_BATTERY - needs discovery schema updated

**Comment by cgarwood** [comment]
this is already done 🤦‍♂️

**Comment by Dinth** [comment]
Im struggling with exposing battery state to HA. The battery state for my devices is visible on Zwave-over-MQTT Integrations page, but i cannot find that information neither as an entity nor attribute anywhere else in HA.
