### ISSUE TITLE
Entity state not correctly reflected in Home Assistant

### ISSUE THREAD

**Issue by bollewolle** [cgarwood/homeassistant-zwave_mqtt#84]
- Home Assistant version: 0.108.3
- ozwdaemon version or add-on version: 1.0.14
- homeassistant-zwave_mqtt version: v0.0.9

To control a light I have a Fibaro Dimmer 2 installed. All seems to be recognized well with zwave over mqtt, all relevant enitities are there. To turn on and turn off the light the entity "FIBARO System FGD212 Dimmer 2: Instance 1: Level" needs to be used. 

However, when I click the button from Off to On, the light does turn on, but directly after the button turns Off again while the light still remains on. Each time I click the button again to On it just goes to Off again while the light remains on. Only a quick succession from Off to On to Off again eventually turns the light off.

So, I've made a quick screenrecording as it probably explains better what I mean than just describing in: https://youtu.be/fb4K9kvy7vw
I tried to describe in the comments what seems to be happening:
***As you can see the initial state in hass is turned off and in MQTT Explorer you can see that the relevant entities value is 0.
When I turn the entity On you can see that the state indeed changes to value 99 and stays on it, but that the button in Home Assistant updates and shows it as turned off. 
Each time you turn it on again the value in MQTT Explorer does not changed and each time the button turns off again.
Only when you quickly click the button on and off again the value is updated to 0 and the light indeed turns off.***

I couldn't find this as a known issue so thought I'd log it. If there's something I can check then please let me know.

**Comment by towerhand** [comment]
Related to #72?

My GE dimmer shows the same behavior.

**Comment by bollewolle** [comment]
You might be right, I thought I read that issue and considered it to be different but when I reread all the comments I believe it's the same. I'll close this issue and will add the info as comment to your ticket.
