### ISSUE TITLE
Recovery after a power fail needs some better support

### ISSUE THREAD

**Issue by kevinkahn** [cgarwood/homeassistant-zwave_mqtt#96]
- Home Assistant version: 108.1
- ozwdaemon version or add-on version: container pull as of 4/19/20

With both HA and OZW running on the same Pi the starting sequences of the 2 systems seems to leave things in a bad state.  Generally what I have seen is that HA starts with most Zwave devices as unavailable.  Restarting OZW will make them become available but control of those devices doesn't work.  Then restarting HA again gets things back in sync.  I understand that currently restarting OZW requires an HA restart so in some sense this indeterminacy is not surprising but before general release this needs to be cleaned up and tested since power restarts will be common for many naive users.

**Comment by marcelveldt** [comment]
This was fixed yesterday. A new version will be pulbished soon.

**Comment by kevinkahn** [comment]
Wow - that was quick service! :-)  Was just documenting it for the future and already handled!
